
export const TRANSLATIONS = {
  de: {
    heroTitle: "Eine Plattform für alle neuen Erlebnisse",
    heroSubtitle: "Finde Konzerte, Sportevents, Restaurants und Karrieremessen in deiner Nähe.",
    searchPlaceholder: "Nach Stadt oder Event suchen...",
    festivent: "Festivent",
    festiventDesc: "Konzerte, Partys & Festivals",
    sports: "Sports",
    sportsDesc: "Regionale & nationale Sportevents",
    dining: "Dining",
    diningDesc: "Restaurants & kulinarische Erlebnisse",
    career: "Career Info",
    careerDesc: "Karrieremessen & Profi-Events",
    login: "Anmelden",
    register: "Registrieren",
    logout: "Abmelden",
    profile: "Profil",
    translate: "English",
    myLocation: "Mein Standort",
    search: "Suchen",
    booking: "Jetzt Buchen",
    cancel: "Stornieren",
    cancelConfirm: "Möchten Sie dieses Event wirklich stornieren?",
    details: "Details ansehen",
    resultsFor: "Ergebnisse für",
    noResults: "Keine Events gefunden. Versuche es mit anderen Suchbegriffen.",
    authModalTitle: "Willkommen bei EventKompass",
    authModalDesc: "Bitte melde dich an, um Events zu buchen.",
    registrationSuccess: "Registrierung erfolgreich! Wir haben dir eine Willkommens-E-Mail mit deinen Zugangsdaten gesendet.",
    loginId: "Benutzer-ID",
    password: "Passwort",
    email: "E-Mail-Adresse",
    fullName: "Vollständiger Name",
    loading: "Wir finden die besten Events für dich...",
    myBookings: "Meine Buchungen",
    noBookings: "Du hast noch keine Events gebucht.",
    bookingSuccess: "Erfolgreich gebucht!",
    alreadyBooked: "Bereits gebucht",
    aboutUs: "Über uns",
    grievances: "Kontakt",
    home: "Home",
    aboutTitle: "Über EventKompass",
    aboutSubtitle: "EventKompass ist Ihr All-in-One-Guide, um die besten Events in ganz Deutschland zu entdecken und zu buchen – schnell, einfach und personalisiert.",
    aboutIntroText: "Egal, ob Sie einen großen Abend planen, ein Stadionerlebnis suchen, einen tollen Ort zum Essen finden möchten oder eine berufliche Netzwerkgelegenheit suchen – wir bringen die relevantesten Optionen auf einer einfachen Plattform zu Ihnen.",
    aboutMissionTitle: "Unsere Mission",
    aboutMissionText: "Wir helfen Menschen dabei, Events zu finden, die ihnen wirklich am Herzen liegen, ohne endloses Suchen auf verschiedenen Websites. Mit intelligenten standortbasierten Vorschlägen und flexibler Regionsauswahl macht es EventKompass mühelos, Erlebnisse in der Nähe oder überall im Land zu planen.",
    aboutWhatWeDoTitle: "Was wir tun",
    aboutWhatWeDoDesc: "EventKompass ist in vier fokussierte Bereiche unterteilt, damit Sie direkt zu dem springen können, was Sie suchen:",
    aboutDifferentTitle: "Warum EventKompass anders ist",
    aboutDifferentLoc: "Standortbezogene Empfehlungen: Priorisieren Sie automatisch Events in der Nähe Ihrer aktuellen Stadt.",
    aboutDifferentExplore: "Über Ihre Stadt hinaus entdecken: Wechseln Sie Regionen manuell für Reisen nach Berlin, München, Hamburg, etc.",
    aboutDifferentLifestyles: "Eine Plattform, vier Lebensstile: Unterhaltung, Sport, Essen und Karriereentwicklung an einem Ort organisiert.",
    aboutDifferentQuick: "Für schnelle Entscheidungen gebaut: Klare Kategorien, maßgeschneiderte Vorschläge und optimierte Buchungen helfen Ihnen, in Minuten zu planen.",
    aboutPromiseTitle: "Unser Versprechen",
    aboutPromiseText: "Egal wo Sie in Deutschland sind oder wohin Sie reisen – EventKompass zeigt Ihnen die richtigen Erlebnisse und hilft Ihnen, diese mit Vertrauen zu buchen. Finden Sie Ihren nächsten Plan. Folgen Sie Ihren Interessen. Lassen Sie sich von EventKompass leiten.",
    aboutChampionsTitle: "Champions unserer Erfolgsgeschichte",
    aboutChampionsText: "EventKompass wird von einer einfachen Idee angetrieben: Menschen dabei zu helfen, die besten Erlebnisse in Deutschland ohne Aufwand zu entdecken und zu buchen. Mit jedem Feature, das wir veröffentlichen, und jeder Partnerschaft, die wir hinzufügen, ist unser konstantes Ziel, die Event-Suche neu zu definieren.",
    aboutFoundersTitle: "Lernen Sie die Gründer hinter EventKompass kennen",
    founderRole: "Mitbegründer",
    grievanceTitle: "Kontakt & Beschwerden",
    grievanceText: "Ihre Zufriedenheit ist uns wichtig. Sollten Sie Probleme mit einer Buchung oder einem Veranstalter haben, teilen Sie uns dies bitte mit.",
    submit: "Absenden",
    share: "Teilen",
    shareTitle: "Dieses Event teilen",
    copyLink: "Link kopieren",
    linkCopied: "Kopiert!",
    shareOn: "Teilen auf"
  },
  en: {
    heroTitle: "One platform for all new experiences",
    heroSubtitle: "Find concerts, sporting events, restaurants, and career fairs near you.",
    searchPlaceholder: "Search by city or event...",
    festivent: "Festivent",
    festiventDesc: "Concerts, Parties & Festivals",
    sports: "Sports",
    sportsDesc: "Regional & national sporting events",
    dining: "Dining",
    diningDesc: "Restaurants & culinary experiences",
    career: "Career Info",
    careerDesc: "Career fairs & professional events",
    login: "Login",
    register: "Register",
    logout: "Logout",
    profile: "Profile",
    translate: "Deutsch",
    myLocation: "My Location",
    search: "Search",
    booking: "Book Now",
    cancel: "Cancel",
    cancelConfirm: "Do you really want to cancel this event?",
    details: "View Details",
    resultsFor: "Results for",
    noResults: "No events found. Try different search terms.",
    authModalTitle: "Welcome to EventKompass",
    authModalDesc: "Please log in to book events.",
    registrationSuccess: "Registration successful! We've sent you a welcome email with your login credentials.",
    loginId: "User ID",
    password: "Password",
    email: "Email Address",
    fullName: "Full Name",
    loading: "Finding the best events for you...",
    myBookings: "My Bookings",
    noBookings: "You haven't booked any events yet.",
    bookingSuccess: "Successfully booked!",
    alreadyBooked: "Already booked",
    aboutUs: "About Us",
    grievances: "Contact Us",
    home: "Home",
    aboutTitle: "About EventKompass",
    aboutSubtitle: "EventKompass is your all-in-one guide to discovering and booking the best events across Germany fast, simple, and personalized.",
    aboutIntroText: "Whether you’re looking for a big night out, a matchday experience, a great place to eat, or a professional networking opportunity, we bring the most relevant options to you in one easy platform.",
    aboutMissionTitle: "Our Mission",
    aboutMissionText: "We help people find events they genuinely care about, without the endless searching across different websites. With smart location-based suggestions and flexible region selection, EventKompass makes it effortless to plan experiences nearby or anywhere in the country.",
    aboutWhatWeDoTitle: "What We Do",
    aboutWhatWeDoDesc: "EventKompass is organized into four focused sections, so you can jump straight to what you want:",
    aboutDifferentTitle: "Why EventKompass is Different",
    aboutDifferentLoc: "Location-aware recommendations: Automatically prioritize events near your current city.",
    aboutDifferentExplore: "Explore beyond your city: Switch regions manually for trips to Berlin, Munich, Hamburg, etc.",
    aboutDifferentLifestyles: "One platform, four lifestyles: Entertainment, sports, food, and career growth organised in one place.",
    aboutDifferentQuick: "Built for quick decisions: Clear categories, tailored suggestions, and streamlined booking help you plan in minutes.",
    aboutPromiseTitle: "Our Promise",
    aboutPromiseText: "No matter where you are in Germany or where you’re heading – EventKompass points you to the right experiences and helps you book them with confidence.",
    aboutChampionsTitle: "Champions of our success story",
    aboutChampionsText: "EventKompass is driven by a simple idea: help people discover and book the best experiences across Germany without the hassle.",
    aboutFoundersTitle: "Meet the founders behind EventKompass",
    founderRole: "Co-Founder",
    grievanceTitle: "Contact & Grievances",
    grievanceText: "Your satisfaction is important to us. If you have issues with a booking or an organizer, please let us know.",
    submit: "Submit",
    share: "Share",
    shareTitle: "Share this event",
    copyLink: "Copy link",
    linkCopied: "Copied!",
    shareOn: "Share on"
  }
};

export const CATEGORY_COLORS = {
  Festivent: "from-purple-600 to-indigo-600",
  Sports: "from-red-600 to-orange-600",
  Dining: "from-emerald-600 to-teal-600",
  Career: "from-slate-700 to-slate-900"
};
