
export const TRANSLATIONS = {
  de: {
    heroTitle: "Eine Plattform für alle neuen Erlebnisse",
    heroSubtitle: "Finde Konzerte, Sportevents, Restaurants und Karrieremessen in deiner Nähe.",
    searchPlaceholder: "Nach Stadt oder Event suchen...",
    festivent: "Festivent",
    festiventDesc: "Konzerte, Partys & Festivals",
    sports: "Sports",
    sportsDesc: "Regionale & nationale Sportevents",
    dining: "Dining",
    diningDesc: "Restaurants & kulinarische Erlebnisse",
    career: "Career Info",
    careerDesc: "Karrieremessen & Profi-Events",
    login: "Anmelden",
    register: "Registrieren",
    logout: "Abmelden",
    profile: "Profil",
    translate: "English",
    myLocation: "Mein Standort",
    search: "Suchen",
    booking: "Jetzt Buchen",
    cancel: "Stornieren",
    cancelConfirm: "Möchten Sie dieses Event wirklich stornieren?",
    details: "Details ansehen",
    resultsFor: "Ergebnisse für",
    noResults: "Keine Events gefunden.",
    authModalTitle: "Willkommen bei EventKompass",
    authModalDesc: "Bitte melde dich an, um Events zu buchen.",
    registrationSuccess: "Registrierung erfolgreich!",
    loginId: "Benutzer-ID",
    password: "Passwort",
    email: "E-Mail-Adresse",
    fullName: "Vollständiger Name",
    mobileNumber: "Mobilnummer",
    profileName: "Profilname (Benutzername)",
    welcomeMailSent: "Willkommens-E-Mail gesendet!",
    welcomeMailDesc: "Prüfen Sie Ihren Posteingang. Wir haben Ihre Zugangsdaten (Benutzername & Passwort) an {email} gesendet.",
    loading: "Wir finden die besten Events für dich...",
    myBookings: "Meine Buchungen",
    noBookings: "Noch keine Events gebucht.",
    bookingSuccess: "Erfolgreich gebucht!",
    alreadyBooked: "Bereits gebucht",
    aboutUs: "Über uns",
    grievances: "Kontakt",
    home: "Home",
    leaveExplorer: "Explorer verlassen",
    currentCuration: "Aktuelle Kuratierung",
    ticketsReservation: "Tickets & Reservierung",
    likeWhatYouSee: "Gefällt Ihnen was Sie sehen?",
    accessNow: "Jetzt zugreifen",
    dontMissEvents: "Verpassen Sie nicht die besten Events in {location}.",
    syncedWithProfile: "Synchronisiert mit Profil",
    metropolises: "Metropolen",
    regions: "Regionen",
    citySuggestions: "Stadt Vorschläge",
    quickChoiceMetro: "Schnellwahl Metropolen",
    current: "Aktuell",
    exploreBtn: "Erkunden",
    topExperiencesMonth: "Top Erlebnisse diesen Monat",
    discoverAll: "Alle entdecken",
    eventHighlight: "Event Highlight",
    premiumMember: "Premium Mitglied",
    accountInfo: "Kontoinformationen",
    customerId: "Kunden-ID",
    editProfile: "Profil bearbeiten",
    confirmQ: "Bestätigen?",
    ticketCount: "Anzahl Tickets",
    totalPrice: "Gesamtpreis",
    verified: "Verifiziert",
    moreInfo: "Mehr Info",
    showMap: "Karte zeigen",
    aiPowered: "KI-gestützte Erfahrung",
    realtimeGrounding: "Echtzeit-Grounding",
    official: "Offiziell",
    bookingIssue: "Buchungsproblem",
    organizerFeedback: "Veranstalter-Feedback",
    technicalIssue: "Technische Störung",
    other: "Sonstiges",
    submit: "Absenden",
    exclusiveCuration: "Exklusive Kuratierung",
    topRecommendations: "Top Empfehlungen",
    // Footer & Links
    platform: "Plattform",
    company: "Unternehmen",
    support: "Support",
    careers: "Karriere",
    press: "Presse",
    contactUs: "Kontaktieren Sie uns",
    helpCenter: "Hilfe-Center",
    partnerProgram: "Partner-Programm",
    imprint: "Impressum",
    privacy: "Datenschutz",
    // Page Content
    aboutTitle: "Über EventKompass",
    aboutSubtitle: "Dein All-in-One Guide für Deutschland.",
    aboutIntroText: "Wir vernetzen Menschen mit den besten Erlebnissen in ihrer Stadt.",
    aboutMissionTitle: "Unsere Mission",
    aboutMissionText: "Wir machen es einfach, Konzerte, Sport und Kultur zu entdecken, ohne stundenlanges Suchen.",
    aboutWhatWeDoTitle: "Was wir tun",
    aboutWhatWeDoDesc: "Vier Säulen für dein perfektes Wochenende.",
    aboutDifferentTitle: "Warum wir anders sind",
    aboutChampionsTitle: "Hinter den Kulissen",
    aboutChampionsText: "Unser Team arbeitet täglich daran, die Plattform für dich zu verbessern.",
    aboutFoundersTitle: "Die Gründer",
    founderRole: "Mitbegründer",
    careersTitle: "Karriere bei EventKompass",
    careersSub: "Gestalte die Zukunft der Event-Entdeckung mit uns. Wir suchen leidenschaftliche Talente für unser Team in Berlin und Darmstadt.",
    engineering: "Engineering",
    marketing: "Marketing",
    job1Title: "Senior Frontend Entwickler (React)",
    job1Desc: "Arbeite an unserer KI-gestützten Suchoberfläche.",
    job2Title: "Growth Marketing Manager",
    job2Desc: "Skaliere EventKompass in neuen deutschen Regionen.",
    pressTitle: "Pressezentrum",
    pressNews1Date: "12. MAI 2025",
    pressNews1Title: "EventKompass knackt 1 Million Buchungen",
    pressNews1Desc: "Innerhalb von nur sechs Monaten hat sich EventKompass zur am schnellsten wachsenden Event-Plattform in der DACH-Region entwickelt.",
    pressNews2Date: "05. APRIL 2025",
    pressNews2Title: "Neue KI-Features für personalisierte Event-Suche",
    pressNews2Desc: "Durch die Integration modernster Sprachmodelle verstehen wir die Wünsche unserer Nutzer besser als je zuvor.",
    grievanceTitle: "Haben Sie ein Anliegen?",
    grievanceText: "Wir sind hier, um zu helfen. Senden Sie uns eine Nachricht und unser Support-Team wird sich so schnell wie möglich bei Ihnen melden.",
    thankYou: "Vielen Dank!",
    messageSuccess: "Ihre Nachricht wurde erfolgreich an unser Team übermittelt. Wir werden uns innerhalb von 24 Stunden bei Ihnen melden.",
    newMessage: "Neue Nachricht",
    subject: "Betreff",
    message: "Nachricht",
    helpPlaceholder: "Wie können wir Ihnen helfen?",
    searchIntelligentPlaceholder: "Was suchst du? (z.B. 'Pizza in Berlin')",
    festivals: "Festivals",
    stadium: "Stadion",
    gourmet: "Gourmet",
    berlinSummerBeats: "Berlin Summer Beats",
    munichDerby: "München Derby Night",
    tasteOfHessen: "Taste of Hessen"
  },
  en: {
    heroTitle: "One platform for all new experiences",
    heroSubtitle: "Find concerts, sporting events, restaurants, and career fairs near you.",
    searchPlaceholder: "Search by city or event...",
    festivent: "Festivent",
    festiventDesc: "Concerts, Parties & Festivals",
    sports: "Sports",
    sportsDesc: "Regional & national sporting events",
    dining: "Dining",
    diningDesc: "Restaurants & culinary experiences",
    career: "Career Info",
    careerDesc: "Career fairs & professional events",
    login: "Login",
    register: "Register",
    logout: "Logout",
    profile: "Profile",
    translate: "Deutsch",
    myLocation: "My Location",
    search: "Search",
    booking: "Book Now",
    cancel: "Cancel",
    cancelConfirm: "Do you really want to cancel this event?",
    details: "View Details",
    resultsFor: "Results for",
    noResults: "No events found.",
    authModalTitle: "Welcome to EventKompass",
    authModalDesc: "Please log in to book events.",
    registrationSuccess: "Registration successful!",
    loginId: "User ID",
    password: "Password",
    email: "Email Address",
    fullName: "Full Name",
    mobileNumber: "Mobile Number",
    profileName: "Profile Name (Username)",
    welcomeMailSent: "Welcome Email Sent!",
    welcomeMailDesc: "Check your inbox. We've sent your credentials (username & password) to {email}.",
    loading: "Finding the best events for you...",
    myBookings: "My Bookings",
    noBookings: "No events booked yet.",
    bookingSuccess: "Successfully booked!",
    alreadyBooked: "Already booked",
    aboutUs: "About Us",
    grievances: "Contact Us",
    home: "Home",
    leaveExplorer: "Leave Explorer",
    currentCuration: "Current Curation",
    ticketsReservation: "Tickets & Reservation",
    likeWhatYouSee: "Like what you see?",
    accessNow: "Access Now",
    dontMissEvents: "Don't miss the best events in {location}.",
    syncedWithProfile: "Synced with profile",
    metropolises: "Metropolises",
    regions: "Regions",
    citySuggestions: "City Suggestions",
    quickChoiceMetro: "Quick Hubs",
    current: "Current",
    exploreBtn: "Explore",
    topExperiencesMonth: "Top Experiences This Month",
    discoverAll: "Discover All",
    eventHighlight: "Event Highlight",
    premiumMember: "Premium Member",
    accountInfo: "Account Info",
    customerId: "Customer ID",
    editProfile: "Edit Profile",
    confirmQ: "Confirm?",
    ticketCount: "Number of Tickets",
    totalPrice: "Total Price",
    verified: "Verified",
    moreInfo: "More Info",
    showMap: "Show Map",
    aiPowered: "AI-Powered Experience",
    realtimeGrounding: "Real-time Grounding",
    official: "Official",
    bookingIssue: "Booking Issue",
    organizerFeedback: "Organizer Feedback",
    technicalIssue: "Technical Issue",
    other: "Other",
    submit: "Submit",
    exclusiveCuration: "Exclusive Curation",
    topRecommendations: "Top Recommendations",
    // Footer & Links
    platform: "Platform",
    company: "Company",
    support: "Support",
    careers: "Careers",
    press: "Press",
    contactUs: "Contact Us",
    helpCenter: "Help Center",
    partnerProgram: "Partner Program",
    imprint: "Imprint",
    privacy: "Privacy",
    // Page Content
    aboutTitle: "About EventKompass",
    aboutSubtitle: "Your All-in-One Guide for Germany.",
    aboutIntroText: "We connect people with the best experiences in their city.",
    aboutMissionTitle: "Our Mission",
    aboutMissionText: "We make it easy to discover concerts, sports, and culture without endless searching.",
    aboutWhatWeDoTitle: "What We Do",
    aboutWhatWeDoDesc: "Four pillars for your perfect weekend.",
    aboutDifferentTitle: "Why We Are Different",
    aboutChampionsTitle: "Behind the Scenes",
    aboutChampionsText: "Our team works daily to improve the platform for you.",
    aboutFoundersTitle: "The Founders",
    founderRole: "Co-Founder",
    careersTitle: "Careers at EventKompass",
    careersSub: "Shape the future of event discovery with us. We are looking for passionate talents for our team in Berlin and Darmstadt.",
    engineering: "Engineering",
    marketing: "Marketing",
    job1Title: "Senior Frontend Developer (React)",
    job1Desc: "Work on our AI-powered search interface.",
    job2Title: "Growth Marketing Manager",
    job2Desc: "Scale EventKompass in new German regions.",
    pressTitle: "Press Center",
    pressNews1Date: "MAY 12, 2025",
    pressNews1Title: "EventKompass hits 1 million bookings",
    pressNews1Desc: "In just six months, EventKompass has become the fastest-growing event platform in the DACH region.",
    pressNews2Date: "APRIL 5, 2025",
    pressNews2Title: "New AI features for personalized event search",
    pressNews2Desc: "By integrating cutting-edge language models, we understand our users' wishes better than ever before.",
    grievanceTitle: "Have a concern?",
    grievanceText: "We are here to help. Send us a message and our support team will get back to you as soon as possible.",
    thankYou: "Thank You!",
    messageSuccess: "Your message has been successfully transmitted to our team. We will get back to you within 24 hours.",
    newMessage: "New Message",
    subject: "Subject",
    message: "Message",
    helpPlaceholder: "How can we help you?",
    searchIntelligentPlaceholder: "What are you looking for? (e.g. 'Pizza in Berlin')",
    festivals: "Festivals",
    stadium: "Stadium",
    gourmet: "Gourmet",
    berlinSummerBeats: "Berlin Summer Beats",
    munichDerby: "Munich Derby Night",
    tasteOfHessen: "Taste of Hessen"
  }
};

export const CATEGORY_COLORS = {
  Festivent: "from-purple-600 to-indigo-600",
  Sports: "from-red-600 to-orange-600",
  Dining: "from-emerald-600 to-teal-600",
  Career: "from-slate-700 to-slate-900"
};

export const GERMAN_CITIES = [
  { name: "Berlin", major: true },
  { name: "Hamburg", major: true },
  { name: "München", major: true },
  { name: "Köln", major: true },
  { name: "Frankfurt am Main", major: true },
  { name: "Stuttgart", major: true },
  { name: "Düsseldorf", major: true },
  { name: "Dortmund", major: true },
  { name: "Essen", major: true },
  { name: "Leipzig", major: true },
  { name: "Bremen", major: true },
  { name: "Dresden", major: true },
  { name: "Hannover", major: true },
  { name: "Nürnberg", major: true },
  { name: "Duisburg", major: true },
  { name: "Bochum", major: true },
  { name: "Wuppertal", major: true },
  { name: "Bielefeld", major: true },
  { name: "Bonn", major: true },
  { name: "Münster", major: true },
  { name: "Karlsruhe", major: false },
  { name: "Mannheim", major: false },
  { name: "Augsburg", major: false },
  { name: "Wiesbaden", major: false },
  { name: "Gelsenkirchen", major: false },
  { name: "Mönchengladbach", major: false },
  { name: "Braunschweig", major: false },
  { name: "Chemnitz", major: false },
  { name: "Kiel", major: false },
  { name: "Aachen", major: false },
  { name: "Halle (Saale)", major: false },
  { name: "Magdeburg", major: false },
  { name: "Freiburg im Breisgau", major: false },
  { name: "Krefeld", major: false },
  { name: "Mainz", major: false },
  { name: "Lübeck", major: false },
  { name: "Erfurt", major: false },
  { name: "Oberhausen", major: false },
  { name: "Rostock", major: false },
  { name: "Kassel", major: false },
  { name: "Hagen", major: false },
  { name: "Potsdam", major: false },
  { name: "Saarbrücken", major: false },
  { name: "Hamm", major: false },
  { name: "Ludwigshafen", major: false },
  { name: "Mülheim an der Ruhr", major: false },
  { name: "Oldenburg", major: false },
  { name: "Osnabrück", major: false },
  { name: "Leverkusen", major: false },
  { name: "Heidelberg", major: false },
  { name: "Darmstadt", major: false },
  { name: "Solingen", major: false },
  { name: "Regensburg", major: false },
  { name: "Herne", major: false },
  { name: "Paderborn", major: false },
  { name: "Neuss", major: false },
  { name: "Offenbach am Main", major: false },
  { name: "Fürth", major: false },
  { name: "Ulm", major: false },
  { name: "Heilbronn", major: false },
  { name: "Pforzheim", major: false },
  { name: "Wolfsburg", major: false },
  { name: "Göttingen", major: false },
  { name: "Bottrop", major: false },
  { name: "Reutlingen", major: false },
  { name: "Koblenz", major: false },
  { name: "Recklinghausen", major: false },
  { name: "Bremerhaven", major: false },
  { name: "Jena", major: false },
  { name: "Remscheid", major: false },
  { name: "Erlangen", major: false },
  { name: "Trier", major: false },
  { name: "Salzgitter", major: false },
  { name: "Cottbus", major: false },
  { name: "Gießen", major: false },
  { name: "Siegen", major: false },
  { name: "Hanau", major: false },
  { name: "Gera", major: false },
  { name: "Iserlohn", major: false },
  { name: "Schwerin", major: false },
  { name: "Düren", major: false },
  { name: "Ratingen", major: false },
  { name: "Zwickau", major: false },
  { name: "Flensburg", major: false },
  { name: "Tübingen", major: false },
  { name: "Worms", major: false },
  { name: "Marl", major: false },
  { name: "Konstanz", major: false },
  { name: "Villingen-Schwenningen", major: false },
  { name: "Lüneburg", major: false },
  { name: "Dessau-Roßlau", major: false },
  { name: "Bamberg", major: false },
  { name: "Viersen", major: false },
  { name: "Marburg", major: false },
  { name: "Rheine", major: false },
  { name: "Wilhelmshaven", major: false },
  { name: "Gladbeck", major: false },
  { name: "Troisdorf", major: false },
  { name: "Minden", major: false },
  { name: "Dorsten", major: false },
  { name: "Lüdenscheid", major: false },
  { name: "Landshut", major: false },
  { name: "Rüsselsheim am Main", major: false },
  { name: "Bocholt", major: false },
  { name: "Herford", major: false },
  { name: "Lippstadt", major: false },
  { name: "Bad Homburg v. d. Höhe", major: false },
  { name: "Balingen", major: false },
  { name: "Querfurt", major: false },
  { name: "Wismar", major: false }
];
